services:
  - type: web
    name: n8n-automation
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-automation.onrender.com
